# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jekyll Statuspage
email: ed@forgenst.com
description: >- # this means to ignore newlines until "baseurl:"
  A descriptive description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://statuspage-starter.vercel.app" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-statuspage

#
# Statuspage-specific Options
#

brand:
    title: Jekyll Statuspage
    logo: /assets/logo.jpg
    logo-text: "Jekyll Statuspage"

color-scheme: dark # blue, dark or red (light is default)
fa-code: "c02bf44fa3" # code for font awesome

site-list:
  links:
    - label: "GitHub" # Name of your website
      url: "https://github.com" # Website URL
      text: "Source Code Hosting" # Optional description
      custom-args: "&color=white&down_color=lightgrey&down_message=offline&label=github.com&logo=github&logoColor=grey&style=for-the-badge&up_color=blue&up_message=online" # Optional Shields.io Badge overrides (see https://shields.io for details, all parameters shown in this example)
    - label: "Atom"
      url: "https://atom.io"
      custom-args: "&logo=atom"
      text: "Text Editor"
    - label: "Blog"
      url: "https://github.blog"
      text: "GitHub Blog"

social:
  links:
    - label: "GitHub"
      icon: "fab fa-github-alt"
      url: "https://github.com/forgenst"
    - label: "Email"
      icon: "far fa-envelope"
      url: "mailto:ed@forgenst.com"
